name: chefio_recipe_app
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_screenutil: ^5.5.3+2
  flutter_svg: ^2.0.9
  pin_code_fields: ^8.0.1
  provider: ^6.0.3
  dotted_border: ^2.0.0+2
  camera: ^0.10.5+4
  path: ^1.8.0
  path_provider: ^2.0.8
  intl: ^0.19.0
  uuid: ^4.3.3
  all_validations_br: ^3.0.0
  equatable: ^2.0.5
  top_snackbar_flutter: ^3.1.0
  image_picker: ^1.0.7
  get_it: ^7.2.0
  fluttertoast: ^8.2.1
  faker: ^2.1.0
  shimmer: ^3.0.0
  cached_network_image: ^3.2.1
  flutter_animate: ^4.2.0
  flutter_slidable: ^3.0.1
  rename: ^3.0.1
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9
  firebase_storage: ^11.6.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/dashboard/
